// Build lock — generated by tools/gen-build-lock.sh, do not hand-edit.
// The carrier refuses to install hooks unless the host exe matches these
// values. Every VA recorded in this project (Ghidra project, src/common/
// game_addresses.h, and future hook tables) is keyed to this exact binary;
// on mismatch, re-RE via the Ghidra project and regenerate this header.
#pragma once

#define MC2_EXPECTED_EXE_SHA256_HEX "7a348847e103d71e8c17e7a51a0f3b4d4422e0c9cb46ec6acc9fe5e4e6be36b5"
#define MC2_EXPECTED_EXE_SIZE_BYTES 53944080ULL
