#!/usr/bin/env bash
# Regenerate src/carrier/build_lock.h from a Mercenaries2.exe.
# The carrier compares this hash/size against the host exe on disk at
# startup and refuses to patch on mismatch (docs/launcher.md: "VAs are
# build-locked").
set -euo pipefail

EXE="${1:?usage: $0 <path-to-Mercenaries2.exe>}"
HEADER="$(cd "$(dirname "$0")/.." && pwd)/src/carrier/build_lock.h"

HASH="$(sha256sum "$EXE" | cut -d' ' -f1)"
SIZE="$(stat -c %s "$EXE")"

cat > "$HEADER" <<EOF
// Build lock — generated by tools/gen-build-lock.sh, do not hand-edit.
// The carrier refuses to install hooks unless the host exe matches these
// values. Every VA recorded in this project (Ghidra project, src/common/
// game_addresses.h, and future hook tables) is keyed to this exact binary;
// on mismatch, re-RE via the Ghidra project and regenerate this header.
#pragma once

#define MC2_EXPECTED_EXE_SHA256_HEX "$HASH"
#define MC2_EXPECTED_EXE_SIZE_BYTES ${SIZE}ULL
EOF

echo "wrote $HEADER"
echo "  sha256 : $HASH"
echo "  size   : $SIZE"
